import KanaKanjiConverterModule

typealias Keymap = [Character: (Character, Character?)]

let fullwidthNumberMap: Keymap = [
    "1": ("１", nil),
    "2": ("２", nil),
    "3": ("３", nil),
    "4": ("４", nil),
    "5": ("５", nil),
    "6": ("６", nil),
    "7": ("７", nil),
    "8": ("８", nil),
    "9": ("９", nil),
    "0": ("０", nil),
]

let fullwidthSymbolMap: Keymap = [
    "!": ("！", nil),
    "\"": ("”", nil),
    "#": ("＃", nil),
    "$": ("＄", nil),
    "%": ("％", nil),
    "&": ("＆", nil),
    "(": ("（", nil),
    ")": ("）", nil),
    "@": ("＠", nil),
    "*": ("＊", nil),
    ":": ("：", nil),
    ";": ("；", nil),
    "?": ("？", nil),
    "^": ("＾", nil),
    "<": ("＜", nil),
    ">": ("＞", nil),
    "=": ("＝", nil),
    "+": ("＋", nil),
    "_": ("＿", nil),
    "`": ("｀", nil),
    "~": ("〜", nil),
    "|": ("｜", nil),
    "[": ("［", nil),
    "]": ("］", nil),
    "/": ("／", nil),
    "\\": ("＼", nil),
]

let fullwidthPeriodMap: Keymap = [
    ".": ("．", nil)
]

let fullwidthCommaMap: Keymap = [
    ",": ("，", nil)
]

let fullwidthJapaneseSymbolMap: Keymap = [
    "-": ("ー", nil),
    "[": ("「", nil),
    "]": ("」", nil),
    "/": ("・", nil),
    "\\": ("￥", nil),
    ",": ("、", nil),
    ".": ("。", nil),
]

let fullwidthSpaceMap: Keymap = [
    " ": ("　", nil)
]

func constructInputTable(
    _ base: [String: String],
) -> InputTable {
    let map: [[InputTable.KeyElement]: [InputTable.ValueElement]] =
        Dictionary(
            uniqueKeysWithValues: base.map { key, value in
                (
                    key.map { InputTable.KeyElement.piece(.character($0)) },
                    value.map { InputTable.ValueElement.character($0) }
                )
            })
    return InputTable(baseMapping: map)
}

let kanaTable = constructInputTable([
    "1": "ぬ",
    "!": "ぬ",
    "2": "ふ",
    "\"": "ふ",
    "3": "あ",
    "#": "ぁ",
    "4": "う",
    "$": "ぅ",
    "5": "え",
    "%": "ぇ",
    "6": "お",
    "&": "ぉ",
    "7": "や",
    "'": "ゃ",
    "8": "ゆ",
    "(": "ゅ",
    "9": "よ",
    ")": "ょ",
    "0": "わ",
    "~": "を",
    "-": "ほ",
    "=": "ほ",
    "^": "へ",
    "\\": "ー",
    "q": "た",
    "Q": "た",
    "w": "て",
    "W": "て",
    "e": "い",
    "E": "ぃ",
    "r": "す",
    "R": "す",
    "t": "か",
    "T": "か",
    "y": "ん",
    "Y": "ん",
    "u": "な",
    "U": "な",
    "i": "に",
    "I": "に",
    "o": "ら",
    "O": "ら",
    "p": "せ",
    "P": "せ",
    "@": "゛",
    "`": "゛",
    "[": "゜",
    "{": "「",
    "a": "ち",
    "A": "ち",
    "s": "と",
    "S": "と",
    "d": "し",
    "D": "し",
    "f": "は",
    "F": "は",
    "g": "き",
    "G": "き",
    "h": "く",
    "H": "く",
    "j": "ま",
    "J": "ま",
    "k": "の",
    "K": "の",
    "l": "り",
    "L": "り",
    ";": "れ",
    "+": "れ",
    ":": "け",
    "*": "け",
    "]": "む",
    "}": "」",
    "z": "つ",
    "Z": "っ",
    "x": "さ",
    "X": "さ",
    "c": "そ",
    "C": "そ",
    "v": "ひ",
    "V": "ひ",
    "b": "こ",
    "B": "こ",
    "n": "み",
    "N": "み",
    "m": "も",
    "M": "も",
    ",": "ね",
    "<": "、",
    ".": "る",
    ">": "。",
    "/": "め",
    "?": "・",
    "_": "ろ",
    "う@": "ゔ",
    "か@": "が",
    "き@": "ぎ",
    "く@": "ぐ",
    "け@": "げ",
    "こ@": "ご",
    "さ@": "ざ",
    "し@": "じ",
    "す@": "ず",
    "せ@": "ぜ",
    "そ@": "ぞ",
    "た@": "だ",
    "ち@": "ぢ",
    "つ@": "づ",
    "て@": "で",
    "と@": "ど",
    "は@": "ば",
    "ひ@": "び",
    "ふ@": "ぶ",
    "へ@": "べ",
    "ほ@": "ぼ",
    "は`": "ぱ",
    "ひ`": "ぴ",
    "ふ`": "ぷ",
    "へ`": "ぺ",
    "ほ`": "ぽ",
])
