// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: base.proto
// Protobuf C++ Version: 6.31.1

#include "base.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace hazkey {

inline constexpr RequestEnvelope::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR RequestEnvelope::RequestEnvelope(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RequestEnvelope_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RequestEnvelopeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestEnvelopeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestEnvelopeDefaultTypeInternal() {}
  union {
    RequestEnvelope _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestEnvelopeDefaultTypeInternal _RequestEnvelope_default_instance_;

inline constexpr ResponseEnvelope::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        error_message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_{static_cast< ::hazkey::StatusCode >(0)},
        payload_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR ResponseEnvelope::ResponseEnvelope(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ResponseEnvelope_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResponseEnvelopeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseEnvelopeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseEnvelopeDefaultTypeInternal() {}
  union {
    ResponseEnvelope _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseEnvelopeDefaultTypeInternal _ResponseEnvelope_default_instance_;
}  // namespace hazkey
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_base_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_base_2eproto = nullptr;
const ::uint32_t
    TableStruct_base_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x004, // bitmap
        PROTOBUF_FIELD_OFFSET(::hazkey::RequestEnvelope, _impl_._oneof_case_[0]),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::hazkey::RequestEnvelope, _impl_.payload_),
        0x085, // bitmap
        PROTOBUF_FIELD_OFFSET(::hazkey::ResponseEnvelope, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::hazkey::ResponseEnvelope, _impl_._oneof_case_[0]),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::hazkey::ResponseEnvelope, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::hazkey::ResponseEnvelope, _impl_.error_message_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::hazkey::ResponseEnvelope, _impl_.payload_),
        1,
        0,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::hazkey::RequestEnvelope)},
        {14, sizeof(::hazkey::ResponseEnvelope)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::hazkey::_RequestEnvelope_default_instance_._instance,
    &::hazkey::_ResponseEnvelope_default_instance_._instance,
};
const char descriptor_table_protodef_base_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nbase.proto\022\006hazkey\032\016commands.proto\"\232\005\n"
    "\017RequestEnvelope\022\?\n\022new_composing_text\030\001"
    " \001(\0132!.hazkey.commands.NewComposingTextH"
    "\000\0220\n\nset_config\030\002 \001(\0132\032.hazkey.commands."
    "SetConfigH\000\0222\n\013set_context\030\003 \001(\0132\033.hazke"
    "y.commands.SetContextH\000\0220\n\ninput_char\030\004 "
    "\001(\0132\032.hazkey.commands.InputCharH\000\0222\n\013mov"
    "e_cursor\030\005 \001(\0132\033.hazkey.commands.MoveCur"
    "sorH\000\022:\n\017prefix_complete\030\006 \001(\0132\037.hazkey."
    "commands.PrefixCompleteH\000\0222\n\013delete_left"
    "\030\007 \001(\0132\033.hazkey.commands.DeleteLeftH\000\0224\n"
    "\014delete_right\030\010 \001(\0132\034.hazkey.commands.De"
    "leteRightH\000\022C\n\024get_composing_string\030\t \001("
    "\0132#.hazkey.commands.GetComposingStringH\000"
    "\022J\n\030get_hiragana_with_cursor\030\n \001(\0132&.haz"
    "key.commands.GetHiraganaWithCursorH\000\0228\n\016"
    "get_candidates\030\013 \001(\0132\036.hazkey.commands.G"
    "etCandidatesH\000B\t\n\007payload\"\241\001\n\020ResponseEn"
    "velope\022\"\n\006status\030\001 \001(\0162\022.hazkey.StatusCo"
    "de\022\025\n\rerror_message\030\002 \001(\t\022\016\n\004text\030\003 \001(\tH"
    "\000\0227\n\ncandidates\030\004 \001(\0132!.hazkey.commands."
    "CandidatesResultH\000B\t\n\007payload*%\n\nStatusC"
    "ode\022\013\n\007SUCCESS\020\000\022\n\n\006FAILED\020\001b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_base_2eproto_deps[1] = {
        &::descriptor_table_commands_2eproto,
};
static ::absl::once_flag descriptor_table_base_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_base_2eproto = {
    false,
    false,
    916,
    descriptor_table_protodef_base_2eproto,
    "base.proto",
    &descriptor_table_base_2eproto_once,
    descriptor_table_base_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_base_2eproto::offsets,
    file_level_enum_descriptors_base_2eproto,
    file_level_service_descriptors_base_2eproto,
};
namespace hazkey {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL StatusCode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_base_2eproto);
  return file_level_enum_descriptors_base_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t StatusCode_internal_data_[] = {
    131072u, 0u, };
// ===================================================================

class RequestEnvelope::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::hazkey::RequestEnvelope, _impl_._oneof_case_);
};

void RequestEnvelope::set_allocated_new_composing_text(::hazkey::commands::NewComposingText* PROTOBUF_NULLABLE new_composing_text) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (new_composing_text) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(new_composing_text)->GetArena();
    if (message_arena != submessage_arena) {
      new_composing_text = ::google::protobuf::internal::GetOwnedMessage(message_arena, new_composing_text, submessage_arena);
    }
    set_has_new_composing_text();
    _impl_.payload_.new_composing_text_ = new_composing_text;
  }
  // @@protoc_insertion_point(field_set_allocated:hazkey.RequestEnvelope.new_composing_text)
}
void RequestEnvelope::clear_new_composing_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kNewComposingText) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.new_composing_text_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.new_composing_text_);
    }
    clear_has_payload();
  }
}
void RequestEnvelope::set_allocated_set_config(::hazkey::commands::SetConfig* PROTOBUF_NULLABLE set_config) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (set_config) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(set_config)->GetArena();
    if (message_arena != submessage_arena) {
      set_config = ::google::protobuf::internal::GetOwnedMessage(message_arena, set_config, submessage_arena);
    }
    set_has_set_config();
    _impl_.payload_.set_config_ = set_config;
  }
  // @@protoc_insertion_point(field_set_allocated:hazkey.RequestEnvelope.set_config)
}
void RequestEnvelope::clear_set_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kSetConfig) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.set_config_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.set_config_);
    }
    clear_has_payload();
  }
}
void RequestEnvelope::set_allocated_set_context(::hazkey::commands::SetContext* PROTOBUF_NULLABLE set_context) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (set_context) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(set_context)->GetArena();
    if (message_arena != submessage_arena) {
      set_context = ::google::protobuf::internal::GetOwnedMessage(message_arena, set_context, submessage_arena);
    }
    set_has_set_context();
    _impl_.payload_.set_context_ = set_context;
  }
  // @@protoc_insertion_point(field_set_allocated:hazkey.RequestEnvelope.set_context)
}
void RequestEnvelope::clear_set_context() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kSetContext) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.set_context_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.set_context_);
    }
    clear_has_payload();
  }
}
void RequestEnvelope::set_allocated_input_char(::hazkey::commands::InputChar* PROTOBUF_NULLABLE input_char) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (input_char) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(input_char)->GetArena();
    if (message_arena != submessage_arena) {
      input_char = ::google::protobuf::internal::GetOwnedMessage(message_arena, input_char, submessage_arena);
    }
    set_has_input_char();
    _impl_.payload_.input_char_ = input_char;
  }
  // @@protoc_insertion_point(field_set_allocated:hazkey.RequestEnvelope.input_char)
}
void RequestEnvelope::clear_input_char() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kInputChar) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.input_char_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.input_char_);
    }
    clear_has_payload();
  }
}
void RequestEnvelope::set_allocated_move_cursor(::hazkey::commands::MoveCursor* PROTOBUF_NULLABLE move_cursor) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (move_cursor) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(move_cursor)->GetArena();
    if (message_arena != submessage_arena) {
      move_cursor = ::google::protobuf::internal::GetOwnedMessage(message_arena, move_cursor, submessage_arena);
    }
    set_has_move_cursor();
    _impl_.payload_.move_cursor_ = move_cursor;
  }
  // @@protoc_insertion_point(field_set_allocated:hazkey.RequestEnvelope.move_cursor)
}
void RequestEnvelope::clear_move_cursor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kMoveCursor) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.move_cursor_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.move_cursor_);
    }
    clear_has_payload();
  }
}
void RequestEnvelope::set_allocated_prefix_complete(::hazkey::commands::PrefixComplete* PROTOBUF_NULLABLE prefix_complete) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (prefix_complete) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(prefix_complete)->GetArena();
    if (message_arena != submessage_arena) {
      prefix_complete = ::google::protobuf::internal::GetOwnedMessage(message_arena, prefix_complete, submessage_arena);
    }
    set_has_prefix_complete();
    _impl_.payload_.prefix_complete_ = prefix_complete;
  }
  // @@protoc_insertion_point(field_set_allocated:hazkey.RequestEnvelope.prefix_complete)
}
void RequestEnvelope::clear_prefix_complete() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kPrefixComplete) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.prefix_complete_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.prefix_complete_);
    }
    clear_has_payload();
  }
}
void RequestEnvelope::set_allocated_delete_left(::hazkey::commands::DeleteLeft* PROTOBUF_NULLABLE delete_left) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (delete_left) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(delete_left)->GetArena();
    if (message_arena != submessage_arena) {
      delete_left = ::google::protobuf::internal::GetOwnedMessage(message_arena, delete_left, submessage_arena);
    }
    set_has_delete_left();
    _impl_.payload_.delete_left_ = delete_left;
  }
  // @@protoc_insertion_point(field_set_allocated:hazkey.RequestEnvelope.delete_left)
}
void RequestEnvelope::clear_delete_left() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kDeleteLeft) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.delete_left_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.delete_left_);
    }
    clear_has_payload();
  }
}
void RequestEnvelope::set_allocated_delete_right(::hazkey::commands::DeleteRight* PROTOBUF_NULLABLE delete_right) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (delete_right) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(delete_right)->GetArena();
    if (message_arena != submessage_arena) {
      delete_right = ::google::protobuf::internal::GetOwnedMessage(message_arena, delete_right, submessage_arena);
    }
    set_has_delete_right();
    _impl_.payload_.delete_right_ = delete_right;
  }
  // @@protoc_insertion_point(field_set_allocated:hazkey.RequestEnvelope.delete_right)
}
void RequestEnvelope::clear_delete_right() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kDeleteRight) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.delete_right_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.delete_right_);
    }
    clear_has_payload();
  }
}
void RequestEnvelope::set_allocated_get_composing_string(::hazkey::commands::GetComposingString* PROTOBUF_NULLABLE get_composing_string) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (get_composing_string) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(get_composing_string)->GetArena();
    if (message_arena != submessage_arena) {
      get_composing_string = ::google::protobuf::internal::GetOwnedMessage(message_arena, get_composing_string, submessage_arena);
    }
    set_has_get_composing_string();
    _impl_.payload_.get_composing_string_ = get_composing_string;
  }
  // @@protoc_insertion_point(field_set_allocated:hazkey.RequestEnvelope.get_composing_string)
}
void RequestEnvelope::clear_get_composing_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kGetComposingString) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.get_composing_string_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.get_composing_string_);
    }
    clear_has_payload();
  }
}
void RequestEnvelope::set_allocated_get_hiragana_with_cursor(::hazkey::commands::GetHiraganaWithCursor* PROTOBUF_NULLABLE get_hiragana_with_cursor) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (get_hiragana_with_cursor) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(get_hiragana_with_cursor)->GetArena();
    if (message_arena != submessage_arena) {
      get_hiragana_with_cursor = ::google::protobuf::internal::GetOwnedMessage(message_arena, get_hiragana_with_cursor, submessage_arena);
    }
    set_has_get_hiragana_with_cursor();
    _impl_.payload_.get_hiragana_with_cursor_ = get_hiragana_with_cursor;
  }
  // @@protoc_insertion_point(field_set_allocated:hazkey.RequestEnvelope.get_hiragana_with_cursor)
}
void RequestEnvelope::clear_get_hiragana_with_cursor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kGetHiraganaWithCursor) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.get_hiragana_with_cursor_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.get_hiragana_with_cursor_);
    }
    clear_has_payload();
  }
}
void RequestEnvelope::set_allocated_get_candidates(::hazkey::commands::GetCandidates* PROTOBUF_NULLABLE get_candidates) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (get_candidates) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(get_candidates)->GetArena();
    if (message_arena != submessage_arena) {
      get_candidates = ::google::protobuf::internal::GetOwnedMessage(message_arena, get_candidates, submessage_arena);
    }
    set_has_get_candidates();
    _impl_.payload_.get_candidates_ = get_candidates;
  }
  // @@protoc_insertion_point(field_set_allocated:hazkey.RequestEnvelope.get_candidates)
}
void RequestEnvelope::clear_get_candidates() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kGetCandidates) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.get_candidates_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.get_candidates_);
    }
    clear_has_payload();
  }
}
RequestEnvelope::RequestEnvelope(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RequestEnvelope_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:hazkey.RequestEnvelope)
}
PROTOBUF_NDEBUG_INLINE RequestEnvelope::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::hazkey::RequestEnvelope& from_msg)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

RequestEnvelope::RequestEnvelope(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RequestEnvelope& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RequestEnvelope_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RequestEnvelope* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kNewComposingText:
        _impl_.payload_.new_composing_text_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.new_composing_text_);
        break;
      case kSetConfig:
        _impl_.payload_.set_config_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.set_config_);
        break;
      case kSetContext:
        _impl_.payload_.set_context_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.set_context_);
        break;
      case kInputChar:
        _impl_.payload_.input_char_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.input_char_);
        break;
      case kMoveCursor:
        _impl_.payload_.move_cursor_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.move_cursor_);
        break;
      case kPrefixComplete:
        _impl_.payload_.prefix_complete_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.prefix_complete_);
        break;
      case kDeleteLeft:
        _impl_.payload_.delete_left_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.delete_left_);
        break;
      case kDeleteRight:
        _impl_.payload_.delete_right_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.delete_right_);
        break;
      case kGetComposingString:
        _impl_.payload_.get_composing_string_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.get_composing_string_);
        break;
      case kGetHiraganaWithCursor:
        _impl_.payload_.get_hiragana_with_cursor_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.get_hiragana_with_cursor_);
        break;
      case kGetCandidates:
        _impl_.payload_.get_candidates_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.get_candidates_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:hazkey.RequestEnvelope)
}
PROTOBUF_NDEBUG_INLINE RequestEnvelope::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void RequestEnvelope::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RequestEnvelope::~RequestEnvelope() {
  // @@protoc_insertion_point(destructor:hazkey.RequestEnvelope)
  SharedDtor(*this);
}
inline void RequestEnvelope::SharedDtor(MessageLite& self) {
  RequestEnvelope& this_ = static_cast<RequestEnvelope&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_payload()) {
    this_.clear_payload();
  }
  this_._impl_.~Impl_();
}

void RequestEnvelope::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:hazkey.RequestEnvelope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kNewComposingText: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.new_composing_text_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.new_composing_text_);
      }
      break;
    }
    case kSetConfig: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.set_config_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.set_config_);
      }
      break;
    }
    case kSetContext: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.set_context_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.set_context_);
      }
      break;
    }
    case kInputChar: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.input_char_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.input_char_);
      }
      break;
    }
    case kMoveCursor: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.move_cursor_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.move_cursor_);
      }
      break;
    }
    case kPrefixComplete: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.prefix_complete_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.prefix_complete_);
      }
      break;
    }
    case kDeleteLeft: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.delete_left_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.delete_left_);
      }
      break;
    }
    case kDeleteRight: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.delete_right_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.delete_right_);
      }
      break;
    }
    case kGetComposingString: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.get_composing_string_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.get_composing_string_);
      }
      break;
    }
    case kGetHiraganaWithCursor: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.get_hiragana_with_cursor_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.get_hiragana_with_cursor_);
      }
      break;
    }
    case kGetCandidates: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.get_candidates_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.get_candidates_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


inline void* PROTOBUF_NONNULL RequestEnvelope::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RequestEnvelope(arena);
}
constexpr auto RequestEnvelope::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RequestEnvelope),
                                            alignof(RequestEnvelope));
}
constexpr auto RequestEnvelope::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RequestEnvelope_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RequestEnvelope::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RequestEnvelope>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RequestEnvelope::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RequestEnvelope>(), &RequestEnvelope::ByteSizeLong,
              &RequestEnvelope::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_._cached_size_),
          false,
      },
      &RequestEnvelope::kDescriptorMethods,
      &descriptor_table_base_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RequestEnvelope_class_data_ =
        RequestEnvelope::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RequestEnvelope::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RequestEnvelope_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RequestEnvelope_class_data_.tc_table);
  return RequestEnvelope_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 11, 11, 0, 2>
RequestEnvelope::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    11, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294965248,  // skipmap
    offsetof(decltype(_table_), field_entries),
    11,  // num_field_entries
    11,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    RequestEnvelope_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::hazkey::RequestEnvelope>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .hazkey.commands.NewComposingText new_composing_text = 1;
    {PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.payload_.new_composing_text_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hazkey.commands.SetConfig set_config = 2;
    {PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.payload_.set_config_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hazkey.commands.SetContext set_context = 3;
    {PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.payload_.set_context_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hazkey.commands.InputChar input_char = 4;
    {PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.payload_.input_char_), _Internal::kOneofCaseOffset + 0, 3,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hazkey.commands.MoveCursor move_cursor = 5;
    {PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.payload_.move_cursor_), _Internal::kOneofCaseOffset + 0, 4,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hazkey.commands.PrefixComplete prefix_complete = 6;
    {PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.payload_.prefix_complete_), _Internal::kOneofCaseOffset + 0, 5,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hazkey.commands.DeleteLeft delete_left = 7;
    {PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.payload_.delete_left_), _Internal::kOneofCaseOffset + 0, 6,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hazkey.commands.DeleteRight delete_right = 8;
    {PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.payload_.delete_right_), _Internal::kOneofCaseOffset + 0, 7,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hazkey.commands.GetComposingString get_composing_string = 9;
    {PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.payload_.get_composing_string_), _Internal::kOneofCaseOffset + 0, 8,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hazkey.commands.GetHiraganaWithCursor get_hiragana_with_cursor = 10;
    {PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.payload_.get_hiragana_with_cursor_), _Internal::kOneofCaseOffset + 0, 9,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hazkey.commands.GetCandidates get_candidates = 11;
    {PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.payload_.get_candidates_), _Internal::kOneofCaseOffset + 0, 10,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::hazkey::commands::NewComposingText>()},
      {::_pbi::TcParser::GetTable<::hazkey::commands::SetConfig>()},
      {::_pbi::TcParser::GetTable<::hazkey::commands::SetContext>()},
      {::_pbi::TcParser::GetTable<::hazkey::commands::InputChar>()},
      {::_pbi::TcParser::GetTable<::hazkey::commands::MoveCursor>()},
      {::_pbi::TcParser::GetTable<::hazkey::commands::PrefixComplete>()},
      {::_pbi::TcParser::GetTable<::hazkey::commands::DeleteLeft>()},
      {::_pbi::TcParser::GetTable<::hazkey::commands::DeleteRight>()},
      {::_pbi::TcParser::GetTable<::hazkey::commands::GetComposingString>()},
      {::_pbi::TcParser::GetTable<::hazkey::commands::GetHiraganaWithCursor>()},
      {::_pbi::TcParser::GetTable<::hazkey::commands::GetCandidates>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void RequestEnvelope::Clear() {
// @@protoc_insertion_point(message_clear_start:hazkey.RequestEnvelope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_payload();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RequestEnvelope::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RequestEnvelope& this_ = static_cast<const RequestEnvelope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RequestEnvelope::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RequestEnvelope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:hazkey.RequestEnvelope)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (this_.payload_case()) {
    case kNewComposingText: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, *this_._impl_.payload_.new_composing_text_, this_._impl_.payload_.new_composing_text_->GetCachedSize(), target,
          stream);
      break;
    }
    case kSetConfig: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *this_._impl_.payload_.set_config_, this_._impl_.payload_.set_config_->GetCachedSize(), target,
          stream);
      break;
    }
    case kSetContext: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *this_._impl_.payload_.set_context_, this_._impl_.payload_.set_context_->GetCachedSize(), target,
          stream);
      break;
    }
    case kInputChar: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, *this_._impl_.payload_.input_char_, this_._impl_.payload_.input_char_->GetCachedSize(), target,
          stream);
      break;
    }
    case kMoveCursor: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          5, *this_._impl_.payload_.move_cursor_, this_._impl_.payload_.move_cursor_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPrefixComplete: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          6, *this_._impl_.payload_.prefix_complete_, this_._impl_.payload_.prefix_complete_->GetCachedSize(), target,
          stream);
      break;
    }
    case kDeleteLeft: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          7, *this_._impl_.payload_.delete_left_, this_._impl_.payload_.delete_left_->GetCachedSize(), target,
          stream);
      break;
    }
    case kDeleteRight: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          8, *this_._impl_.payload_.delete_right_, this_._impl_.payload_.delete_right_->GetCachedSize(), target,
          stream);
      break;
    }
    case kGetComposingString: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          9, *this_._impl_.payload_.get_composing_string_, this_._impl_.payload_.get_composing_string_->GetCachedSize(), target,
          stream);
      break;
    }
    case kGetHiraganaWithCursor: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          10, *this_._impl_.payload_.get_hiragana_with_cursor_, this_._impl_.payload_.get_hiragana_with_cursor_->GetCachedSize(), target,
          stream);
      break;
    }
    case kGetCandidates: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          11, *this_._impl_.payload_.get_candidates_, this_._impl_.payload_.get_candidates_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hazkey.RequestEnvelope)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RequestEnvelope::ByteSizeLong(const MessageLite& base) {
  const RequestEnvelope& this_ = static_cast<const RequestEnvelope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RequestEnvelope::ByteSizeLong() const {
  const RequestEnvelope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:hazkey.RequestEnvelope)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  switch (this_.payload_case()) {
    // .hazkey.commands.NewComposingText new_composing_text = 1;
    case kNewComposingText: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.new_composing_text_);
      break;
    }
    // .hazkey.commands.SetConfig set_config = 2;
    case kSetConfig: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.set_config_);
      break;
    }
    // .hazkey.commands.SetContext set_context = 3;
    case kSetContext: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.set_context_);
      break;
    }
    // .hazkey.commands.InputChar input_char = 4;
    case kInputChar: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.input_char_);
      break;
    }
    // .hazkey.commands.MoveCursor move_cursor = 5;
    case kMoveCursor: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.move_cursor_);
      break;
    }
    // .hazkey.commands.PrefixComplete prefix_complete = 6;
    case kPrefixComplete: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.prefix_complete_);
      break;
    }
    // .hazkey.commands.DeleteLeft delete_left = 7;
    case kDeleteLeft: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.delete_left_);
      break;
    }
    // .hazkey.commands.DeleteRight delete_right = 8;
    case kDeleteRight: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.delete_right_);
      break;
    }
    // .hazkey.commands.GetComposingString get_composing_string = 9;
    case kGetComposingString: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.get_composing_string_);
      break;
    }
    // .hazkey.commands.GetHiraganaWithCursor get_hiragana_with_cursor = 10;
    case kGetHiraganaWithCursor: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.get_hiragana_with_cursor_);
      break;
    }
    // .hazkey.commands.GetCandidates get_candidates = 11;
    case kGetCandidates: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.get_candidates_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RequestEnvelope::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RequestEnvelope*>(&to_msg);
  auto& from = static_cast<const RequestEnvelope&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:hazkey.RequestEnvelope)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kNewComposingText: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.new_composing_text_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.new_composing_text_);
        } else {
          _this->_impl_.payload_.new_composing_text_->MergeFrom(*from._impl_.payload_.new_composing_text_);
        }
        break;
      }
      case kSetConfig: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.set_config_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.set_config_);
        } else {
          _this->_impl_.payload_.set_config_->MergeFrom(*from._impl_.payload_.set_config_);
        }
        break;
      }
      case kSetContext: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.set_context_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.set_context_);
        } else {
          _this->_impl_.payload_.set_context_->MergeFrom(*from._impl_.payload_.set_context_);
        }
        break;
      }
      case kInputChar: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.input_char_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.input_char_);
        } else {
          _this->_impl_.payload_.input_char_->MergeFrom(*from._impl_.payload_.input_char_);
        }
        break;
      }
      case kMoveCursor: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.move_cursor_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.move_cursor_);
        } else {
          _this->_impl_.payload_.move_cursor_->MergeFrom(*from._impl_.payload_.move_cursor_);
        }
        break;
      }
      case kPrefixComplete: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.prefix_complete_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.prefix_complete_);
        } else {
          _this->_impl_.payload_.prefix_complete_->MergeFrom(*from._impl_.payload_.prefix_complete_);
        }
        break;
      }
      case kDeleteLeft: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.delete_left_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.delete_left_);
        } else {
          _this->_impl_.payload_.delete_left_->MergeFrom(*from._impl_.payload_.delete_left_);
        }
        break;
      }
      case kDeleteRight: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.delete_right_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.delete_right_);
        } else {
          _this->_impl_.payload_.delete_right_->MergeFrom(*from._impl_.payload_.delete_right_);
        }
        break;
      }
      case kGetComposingString: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.get_composing_string_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.get_composing_string_);
        } else {
          _this->_impl_.payload_.get_composing_string_->MergeFrom(*from._impl_.payload_.get_composing_string_);
        }
        break;
      }
      case kGetHiraganaWithCursor: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.get_hiragana_with_cursor_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.get_hiragana_with_cursor_);
        } else {
          _this->_impl_.payload_.get_hiragana_with_cursor_->MergeFrom(*from._impl_.payload_.get_hiragana_with_cursor_);
        }
        break;
      }
      case kGetCandidates: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.get_candidates_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.get_candidates_);
        } else {
          _this->_impl_.payload_.get_candidates_->MergeFrom(*from._impl_.payload_.get_candidates_);
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RequestEnvelope::CopyFrom(const RequestEnvelope& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hazkey.RequestEnvelope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RequestEnvelope::InternalSwap(RequestEnvelope* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata RequestEnvelope::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ResponseEnvelope::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ResponseEnvelope>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::hazkey::ResponseEnvelope, _impl_._oneof_case_);
};

void ResponseEnvelope::set_allocated_candidates(::hazkey::commands::CandidatesResult* PROTOBUF_NULLABLE candidates) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (candidates) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(candidates)->GetArena();
    if (message_arena != submessage_arena) {
      candidates = ::google::protobuf::internal::GetOwnedMessage(message_arena, candidates, submessage_arena);
    }
    set_has_candidates();
    _impl_.payload_.candidates_ = candidates;
  }
  // @@protoc_insertion_point(field_set_allocated:hazkey.ResponseEnvelope.candidates)
}
void ResponseEnvelope::clear_candidates() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kCandidates) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.candidates_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.candidates_);
    }
    clear_has_payload();
  }
}
ResponseEnvelope::ResponseEnvelope(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ResponseEnvelope_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:hazkey.ResponseEnvelope)
}
PROTOBUF_NDEBUG_INLINE ResponseEnvelope::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::hazkey::ResponseEnvelope& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        error_message_(arena, from.error_message_),
        payload_{},
        _oneof_case_{from._oneof_case_[0]} {}

ResponseEnvelope::ResponseEnvelope(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ResponseEnvelope& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ResponseEnvelope_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ResponseEnvelope* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.status_ = from._impl_.status_;
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kText:
        new (&_impl_.payload_.text_) decltype(_impl_.payload_.text_){arena, from._impl_.payload_.text_};
        break;
      case kCandidates:
        _impl_.payload_.candidates_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.candidates_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:hazkey.ResponseEnvelope)
}
PROTOBUF_NDEBUG_INLINE ResponseEnvelope::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        error_message_(arena),
        payload_{},
        _oneof_case_{} {}

inline void ResponseEnvelope::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
ResponseEnvelope::~ResponseEnvelope() {
  // @@protoc_insertion_point(destructor:hazkey.ResponseEnvelope)
  SharedDtor(*this);
}
inline void ResponseEnvelope::SharedDtor(MessageLite& self) {
  ResponseEnvelope& this_ = static_cast<ResponseEnvelope&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.error_message_.Destroy();
  if (this_.has_payload()) {
    this_.clear_payload();
  }
  this_._impl_.~Impl_();
}

void ResponseEnvelope::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:hazkey.ResponseEnvelope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kText: {
      _impl_.payload_.text_.Destroy();
      break;
    }
    case kCandidates: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.candidates_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.candidates_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


inline void* PROTOBUF_NONNULL ResponseEnvelope::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ResponseEnvelope(arena);
}
constexpr auto ResponseEnvelope::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ResponseEnvelope),
                                            alignof(ResponseEnvelope));
}
constexpr auto ResponseEnvelope::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ResponseEnvelope_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ResponseEnvelope::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ResponseEnvelope>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ResponseEnvelope::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ResponseEnvelope>(), &ResponseEnvelope::ByteSizeLong,
              &ResponseEnvelope::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_._cached_size_),
          false,
      },
      &ResponseEnvelope::kDescriptorMethods,
      &descriptor_table_base_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ResponseEnvelope_class_data_ =
        ResponseEnvelope::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ResponseEnvelope::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ResponseEnvelope_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ResponseEnvelope_class_data_.tc_table);
  return ResponseEnvelope_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 4, 1, 49, 2>
ResponseEnvelope::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_._has_bits_),
    0, // no _extensions_
    4, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ResponseEnvelope_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::hazkey::ResponseEnvelope>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string error_message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.error_message_)}},
    // .hazkey.StatusCode status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResponseEnvelope, _impl_.status_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .hazkey.StatusCode status = 1;
    {PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.status_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string error_message = 2;
    {PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.error_message_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string text = 3;
    {PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.payload_.text_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .hazkey.commands.CandidatesResult candidates = 4;
    {PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.payload_.candidates_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::hazkey::commands::CandidatesResult>()},
  }},
  {{
    "\27\0\15\4\0\0\0\0"
    "hazkey.ResponseEnvelope"
    "error_message"
    "text"
  }},
};
PROTOBUF_NOINLINE void ResponseEnvelope::Clear() {
// @@protoc_insertion_point(message_clear_start:hazkey.ResponseEnvelope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.error_message_.ClearNonDefaultToEmpty();
  }
  _impl_.status_ = 0;
  clear_payload();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ResponseEnvelope::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ResponseEnvelope& this_ = static_cast<const ResponseEnvelope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ResponseEnvelope::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ResponseEnvelope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:hazkey.ResponseEnvelope)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .hazkey.StatusCode status = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_status(), target);
    }
  }

  // string error_message = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_error_message().empty()) {
      const ::std::string& _s = this_._internal_error_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "hazkey.ResponseEnvelope.error_message");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  switch (this_.payload_case()) {
    case kText: {
      const ::std::string& _s = this_._internal_text();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "hazkey.ResponseEnvelope.text");
      target = stream->WriteStringMaybeAliased(3, _s, target);
      break;
    }
    case kCandidates: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, *this_._impl_.payload_.candidates_, this_._impl_.payload_.candidates_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hazkey.ResponseEnvelope)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ResponseEnvelope::ByteSizeLong(const MessageLite& base) {
  const ResponseEnvelope& this_ = static_cast<const ResponseEnvelope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ResponseEnvelope::ByteSizeLong() const {
  const ResponseEnvelope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:hazkey.ResponseEnvelope)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // string error_message = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_error_message().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_error_message());
      }
    }
    // .hazkey.StatusCode status = 1;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
  }
  switch (this_.payload_case()) {
    // string text = 3;
    case kText: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_text());
      break;
    }
    // .hazkey.commands.CandidatesResult candidates = 4;
    case kCandidates: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.candidates_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ResponseEnvelope::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ResponseEnvelope*>(&to_msg);
  auto& from = static_cast<const ResponseEnvelope&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:hazkey.ResponseEnvelope)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_error_message().empty()) {
        _this->_internal_set_error_message(from._internal_error_message());
      } else {
        if (_this->_impl_.error_message_.IsDefault()) {
          _this->_internal_set_error_message("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kText: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.text_.InitDefault();
        }
        _this->_impl_.payload_.text_.Set(from._internal_text(), arena);
        break;
      }
      case kCandidates: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.candidates_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.candidates_);
        } else {
          _this->_impl_.payload_.candidates_->MergeFrom(*from._impl_.payload_.candidates_);
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResponseEnvelope::CopyFrom(const ResponseEnvelope& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hazkey.ResponseEnvelope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ResponseEnvelope::InternalSwap(ResponseEnvelope* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_message_, &other->_impl_.error_message_, arena);
  swap(_impl_.status_, other->_impl_.status_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata ResponseEnvelope::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace hazkey
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_base_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
