// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: config.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Hazkey_Config_ConfigFileHashes: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fileHashes: [Hazkey_Config_ConfigFileHashes.FileHash] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct FileHash: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var path: String = String()

    var sha256Sum: String = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}
}

struct Hazkey_Config_ConfigProfile: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var profileName: String {
    get {return _storage._profileName}
    set {_uniqueStorage()._profileName = newValue}
  }

  var autoConvertMode: Hazkey_Config_ConfigProfile.AutoConvertMode {
    get {return _storage._autoConvertMode}
    set {_uniqueStorage()._autoConvertMode = newValue}
  }

  var auxTextMode: Hazkey_Config_ConfigProfile.AuxTextMode {
    get {return _storage._auxTextMode}
    set {_uniqueStorage()._auxTextMode = newValue}
  }

  var suggestionListMode: Hazkey_Config_ConfigProfile.SuggestionListMode {
    get {return _storage._suggestionListMode}
    set {_uniqueStorage()._suggestionListMode = newValue}
  }

  var useWiseSuggestion: Bool {
    get {return _storage._useWiseSuggestion}
    set {_uniqueStorage()._useWiseSuggestion = newValue}
  }

  var numSuggestions: Int32 {
    get {return _storage._numSuggestions}
    set {_uniqueStorage()._numSuggestions = newValue}
  }

  var numCandidatesPerPage: Int32 {
    get {return _storage._numCandidatesPerPage}
    set {_uniqueStorage()._numCandidatesPerPage = newValue}
  }

  var useWiseCandidates: Bool {
    get {return _storage._useWiseCandidates}
    set {_uniqueStorage()._useWiseCandidates = newValue}
  }

  var useInputHistory: Bool {
    get {return _storage._useInputHistory}
    set {_uniqueStorage()._useInputHistory = newValue}
  }

  var stopStoreNewHistory: Bool {
    get {return _storage._stopStoreNewHistory}
    set {_uniqueStorage()._stopStoreNewHistory = newValue}
  }

  var specialConversionMode: Hazkey_Config_ConfigProfile.SpecialConversionMode {
    get {return _storage._specialConversionMode ?? Hazkey_Config_ConfigProfile.SpecialConversionMode()}
    set {_uniqueStorage()._specialConversionMode = newValue}
  }
  /// Returns true if `specialConversionMode` has been explicitly set.
  var hasSpecialConversionMode: Bool {return _storage._specialConversionMode != nil}
  /// Clears the value of `specialConversionMode`. Subsequent reads from it will return its default value.
  mutating func clearSpecialConversionMode() {_uniqueStorage()._specialConversionMode = nil}

  var enabledTables: [Hazkey_Config_ConfigProfile.InputTable] {
    get {return _storage._enabledTables}
    set {_uniqueStorage()._enabledTables = newValue}
  }

  var zenzaiEnable: Bool {
    get {return _storage._zenzaiEnable}
    set {_uniqueStorage()._zenzaiEnable = newValue}
  }

  var zenzaiInferLimit: Int32 {
    get {return _storage._zenzaiInferLimit}
    set {_uniqueStorage()._zenzaiInferLimit = newValue}
  }

  var zenzaiContextualMode: Bool {
    get {return _storage._zenzaiContextualMode}
    set {_uniqueStorage()._zenzaiContextualMode = newValue}
  }

  var zenzaiVersionConfig: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig {
    get {return _storage._zenzaiVersionConfig ?? Hazkey_Config_ConfigProfile.ZenzaiVersionConfig()}
    set {_uniqueStorage()._zenzaiVersionConfig = newValue}
  }
  /// Returns true if `zenzaiVersionConfig` has been explicitly set.
  var hasZenzaiVersionConfig: Bool {return _storage._zenzaiVersionConfig != nil}
  /// Clears the value of `zenzaiVersionConfig`. Subsequent reads from it will return its default value.
  mutating func clearZenzaiVersionConfig() {_uniqueStorage()._zenzaiVersionConfig = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum AutoConvertMode: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unspecified // = 0
    case autoConvertNever // = 1
    case autoConvertAlways // = 2
    case autoConvertAfterSecondCharacter // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .autoConvertNever
      case 2: self = .autoConvertAlways
      case 3: self = .autoConvertAfterSecondCharacter
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .autoConvertNever: return 1
      case .autoConvertAlways: return 2
      case .autoConvertAfterSecondCharacter: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Hazkey_Config_ConfigProfile.AutoConvertMode] = [
      .unspecified,
      .autoConvertNever,
      .autoConvertAlways,
      .autoConvertAfterSecondCharacter,
    ]

  }

  enum AuxTextMode: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unspecified // = 0
    case auxTextShowNever // = 1
    case auxTextShowAlways // = 2
    case auxTextShowWhenCursorNotAtEnd // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .auxTextShowNever
      case 2: self = .auxTextShowAlways
      case 3: self = .auxTextShowWhenCursorNotAtEnd
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .auxTextShowNever: return 1
      case .auxTextShowAlways: return 2
      case .auxTextShowWhenCursorNotAtEnd: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Hazkey_Config_ConfigProfile.AuxTextMode] = [
      .unspecified,
      .auxTextShowNever,
      .auxTextShowAlways,
      .auxTextShowWhenCursorNotAtEnd,
    ]

  }

  enum SuggestionListMode: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unspecified // = 0
    case suggestionListShowNever // = 1
    case suggestionListShowNormalResults // = 2
    case suggestionListShowPredictiveResults // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .suggestionListShowNever
      case 2: self = .suggestionListShowNormalResults
      case 3: self = .suggestionListShowPredictiveResults
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .suggestionListShowNever: return 1
      case .suggestionListShowNormalResults: return 2
      case .suggestionListShowPredictiveResults: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Hazkey_Config_ConfigProfile.SuggestionListMode] = [
      .unspecified,
      .suggestionListShowNever,
      .suggestionListShowNormalResults,
      .suggestionListShowPredictiveResults,
    ]

  }

  struct SpecialConversionMode: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var commaSeparatedNumber: Bool = false

    var mailDomain: Bool = false

    var calender: Bool = false

    var time: Bool = false

    var romanTypography: Bool = false

    var unicodeCodepoint: Bool = false

    var hazkeyVersion: Bool = false

    var halfwidthKatakana: Bool = false

    var extendedEmoji: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  struct InputTable: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var name: String = String()

    var isDefault: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  struct ZenzaiVersionConfig: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var version: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.OneOf_Version? = nil

    var v1: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V1 {
      get {
        if case .v1(let v)? = version {return v}
        return Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V1()
      }
      set {version = .v1(newValue)}
    }

    var v2: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V2 {
      get {
        if case .v2(let v)? = version {return v}
        return Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V2()
      }
      set {version = .v2(newValue)}
    }

    var v3: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V3 {
      get {
        if case .v3(let v)? = version {return v}
        return Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V3()
      }
      set {version = .v3(newValue)}
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum OneOf_Version: Equatable, Sendable {
      case v1(Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V1)
      case v2(Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V2)
      case v3(Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V3)

    }

    struct V1: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    struct V2: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var profile: String = String()

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    struct V3: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var profile: String = String()

      var topic: String = String()

      var style: String = String()

      var preference: String = String()

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    init() {}
  }

  struct ZenzaiModel: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var name: String = String()

    var filename: String = String()

    var isSystem: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Hazkey_Config_getCurrentConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Hazkey_Config_setConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var hash: Hazkey_Config_ConfigFileHashes {
    get {return _hash ?? Hazkey_Config_ConfigFileHashes()}
    set {_hash = newValue}
  }
  /// Returns true if `hash` has been explicitly set.
  var hasHash: Bool {return self._hash != nil}
  /// Clears the value of `hash`. Subsequent reads from it will return its default value.
  mutating func clearHash() {self._hash = nil}

  var tableOperations: [Hazkey_Config_Table_EditOperation] = []

  var config: [Hazkey_Config_ConfigProfile] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _hash: Hazkey_Config_ConfigFileHashes? = nil
}

struct Hazkey_Config_getDefaultConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Hazkey_Config_clearAllHistory: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Hazkey_Config_CurrentConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var hash: Hazkey_Config_ConfigFileHashes {
    get {return _hash ?? Hazkey_Config_ConfigFileHashes()}
    set {_hash = newValue}
  }
  /// Returns true if `hash` has been explicitly set.
  var hasHash: Bool {return self._hash != nil}
  /// Clears the value of `hash`. Subsequent reads from it will return its default value.
  mutating func clearHash() {self._hash = nil}

  var inputTables: [Hazkey_Config_Table_InputTable] = []

  var configs: [Hazkey_Config_ConfigProfile] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _hash: Hazkey_Config_ConfigFileHashes? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "hazkey.config"

extension Hazkey_Config_ConfigFileHashes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConfigFileHashes"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "file_hashes"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.fileHashes) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fileHashes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.fileHashes, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_ConfigFileHashes, rhs: Hazkey_Config_ConfigFileHashes) -> Bool {
    if lhs.fileHashes != rhs.fileHashes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_Config_ConfigFileHashes.FileHash: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Hazkey_Config_ConfigFileHashes.protoMessageName + ".FileHash"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "path"),
    2: .same(proto: "sha256sum"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.sha256Sum) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 1)
    }
    if !self.sha256Sum.isEmpty {
      try visitor.visitSingularStringField(value: self.sha256Sum, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_ConfigFileHashes.FileHash, rhs: Hazkey_Config_ConfigFileHashes.FileHash) -> Bool {
    if lhs.path != rhs.path {return false}
    if lhs.sha256Sum != rhs.sha256Sum {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_Config_ConfigProfile: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConfigProfile"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    5: .standard(proto: "profile_name"),
    10: .standard(proto: "auto_convert_mode"),
    11: .standard(proto: "aux_text_mode"),
    12: .standard(proto: "suggestion_list_mode"),
    13: .standard(proto: "use_wise_suggestion"),
    14: .standard(proto: "num_suggestions"),
    15: .standard(proto: "num_candidates_per_page"),
    16: .standard(proto: "use_wise_candidates"),
    20: .standard(proto: "use_input_history"),
    21: .standard(proto: "stop_store_new_history"),
    30: .standard(proto: "special_conversion_mode"),
    40: .standard(proto: "enabled_tables"),
    100: .standard(proto: "zenzai_enable"),
    101: .standard(proto: "zenzai_infer_limit"),
    102: .standard(proto: "zenzai_contextual_mode"),
    103: .standard(proto: "zenzai_version_config"),
  ]

  fileprivate class _StorageClass {
    var _profileName: String = String()
    var _autoConvertMode: Hazkey_Config_ConfigProfile.AutoConvertMode = .unspecified
    var _auxTextMode: Hazkey_Config_ConfigProfile.AuxTextMode = .unspecified
    var _suggestionListMode: Hazkey_Config_ConfigProfile.SuggestionListMode = .unspecified
    var _useWiseSuggestion: Bool = false
    var _numSuggestions: Int32 = 0
    var _numCandidatesPerPage: Int32 = 0
    var _useWiseCandidates: Bool = false
    var _useInputHistory: Bool = false
    var _stopStoreNewHistory: Bool = false
    var _specialConversionMode: Hazkey_Config_ConfigProfile.SpecialConversionMode? = nil
    var _enabledTables: [Hazkey_Config_ConfigProfile.InputTable] = []
    var _zenzaiEnable: Bool = false
    var _zenzaiInferLimit: Int32 = 0
    var _zenzaiContextualMode: Bool = false
    var _zenzaiVersionConfig: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _profileName = source._profileName
      _autoConvertMode = source._autoConvertMode
      _auxTextMode = source._auxTextMode
      _suggestionListMode = source._suggestionListMode
      _useWiseSuggestion = source._useWiseSuggestion
      _numSuggestions = source._numSuggestions
      _numCandidatesPerPage = source._numCandidatesPerPage
      _useWiseCandidates = source._useWiseCandidates
      _useInputHistory = source._useInputHistory
      _stopStoreNewHistory = source._stopStoreNewHistory
      _specialConversionMode = source._specialConversionMode
      _enabledTables = source._enabledTables
      _zenzaiEnable = source._zenzaiEnable
      _zenzaiInferLimit = source._zenzaiInferLimit
      _zenzaiContextualMode = source._zenzaiContextualMode
      _zenzaiVersionConfig = source._zenzaiVersionConfig
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._profileName) }()
        case 10: try { try decoder.decodeSingularEnumField(value: &_storage._autoConvertMode) }()
        case 11: try { try decoder.decodeSingularEnumField(value: &_storage._auxTextMode) }()
        case 12: try { try decoder.decodeSingularEnumField(value: &_storage._suggestionListMode) }()
        case 13: try { try decoder.decodeSingularBoolField(value: &_storage._useWiseSuggestion) }()
        case 14: try { try decoder.decodeSingularInt32Field(value: &_storage._numSuggestions) }()
        case 15: try { try decoder.decodeSingularInt32Field(value: &_storage._numCandidatesPerPage) }()
        case 16: try { try decoder.decodeSingularBoolField(value: &_storage._useWiseCandidates) }()
        case 20: try { try decoder.decodeSingularBoolField(value: &_storage._useInputHistory) }()
        case 21: try { try decoder.decodeSingularBoolField(value: &_storage._stopStoreNewHistory) }()
        case 30: try { try decoder.decodeSingularMessageField(value: &_storage._specialConversionMode) }()
        case 40: try { try decoder.decodeRepeatedMessageField(value: &_storage._enabledTables) }()
        case 100: try { try decoder.decodeSingularBoolField(value: &_storage._zenzaiEnable) }()
        case 101: try { try decoder.decodeSingularInt32Field(value: &_storage._zenzaiInferLimit) }()
        case 102: try { try decoder.decodeSingularBoolField(value: &_storage._zenzaiContextualMode) }()
        case 103: try { try decoder.decodeSingularMessageField(value: &_storage._zenzaiVersionConfig) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._profileName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._profileName, fieldNumber: 5)
      }
      if _storage._autoConvertMode != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._autoConvertMode, fieldNumber: 10)
      }
      if _storage._auxTextMode != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._auxTextMode, fieldNumber: 11)
      }
      if _storage._suggestionListMode != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._suggestionListMode, fieldNumber: 12)
      }
      if _storage._useWiseSuggestion != false {
        try visitor.visitSingularBoolField(value: _storage._useWiseSuggestion, fieldNumber: 13)
      }
      if _storage._numSuggestions != 0 {
        try visitor.visitSingularInt32Field(value: _storage._numSuggestions, fieldNumber: 14)
      }
      if _storage._numCandidatesPerPage != 0 {
        try visitor.visitSingularInt32Field(value: _storage._numCandidatesPerPage, fieldNumber: 15)
      }
      if _storage._useWiseCandidates != false {
        try visitor.visitSingularBoolField(value: _storage._useWiseCandidates, fieldNumber: 16)
      }
      if _storage._useInputHistory != false {
        try visitor.visitSingularBoolField(value: _storage._useInputHistory, fieldNumber: 20)
      }
      if _storage._stopStoreNewHistory != false {
        try visitor.visitSingularBoolField(value: _storage._stopStoreNewHistory, fieldNumber: 21)
      }
      try { if let v = _storage._specialConversionMode {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 30)
      } }()
      if !_storage._enabledTables.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._enabledTables, fieldNumber: 40)
      }
      if _storage._zenzaiEnable != false {
        try visitor.visitSingularBoolField(value: _storage._zenzaiEnable, fieldNumber: 100)
      }
      if _storage._zenzaiInferLimit != 0 {
        try visitor.visitSingularInt32Field(value: _storage._zenzaiInferLimit, fieldNumber: 101)
      }
      if _storage._zenzaiContextualMode != false {
        try visitor.visitSingularBoolField(value: _storage._zenzaiContextualMode, fieldNumber: 102)
      }
      try { if let v = _storage._zenzaiVersionConfig {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 103)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_ConfigProfile, rhs: Hazkey_Config_ConfigProfile) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._profileName != rhs_storage._profileName {return false}
        if _storage._autoConvertMode != rhs_storage._autoConvertMode {return false}
        if _storage._auxTextMode != rhs_storage._auxTextMode {return false}
        if _storage._suggestionListMode != rhs_storage._suggestionListMode {return false}
        if _storage._useWiseSuggestion != rhs_storage._useWiseSuggestion {return false}
        if _storage._numSuggestions != rhs_storage._numSuggestions {return false}
        if _storage._numCandidatesPerPage != rhs_storage._numCandidatesPerPage {return false}
        if _storage._useWiseCandidates != rhs_storage._useWiseCandidates {return false}
        if _storage._useInputHistory != rhs_storage._useInputHistory {return false}
        if _storage._stopStoreNewHistory != rhs_storage._stopStoreNewHistory {return false}
        if _storage._specialConversionMode != rhs_storage._specialConversionMode {return false}
        if _storage._enabledTables != rhs_storage._enabledTables {return false}
        if _storage._zenzaiEnable != rhs_storage._zenzaiEnable {return false}
        if _storage._zenzaiInferLimit != rhs_storage._zenzaiInferLimit {return false}
        if _storage._zenzaiContextualMode != rhs_storage._zenzaiContextualMode {return false}
        if _storage._zenzaiVersionConfig != rhs_storage._zenzaiVersionConfig {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_Config_ConfigProfile.AutoConvertMode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "AUTO_CONVERT_MODE_UNSPECIFIED"),
    1: .same(proto: "AUTO_CONVERT_NEVER"),
    2: .same(proto: "AUTO_CONVERT_ALWAYS"),
    3: .same(proto: "AUTO_CONVERT_AFTER_SECOND_CHARACTER"),
  ]
}

extension Hazkey_Config_ConfigProfile.AuxTextMode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "AUX_TEXT_MODE_UNSPECIFIED"),
    1: .same(proto: "AUX_TEXT_SHOW_NEVER"),
    2: .same(proto: "AUX_TEXT_SHOW_ALWAYS"),
    3: .same(proto: "AUX_TEXT_SHOW_WHEN_CURSOR_NOT_AT_END"),
  ]
}

extension Hazkey_Config_ConfigProfile.SuggestionListMode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "SUGGESTION_LIST_MODE_UNSPECIFIED"),
    1: .same(proto: "SUGGESTION_LIST_SHOW_NEVER"),
    2: .same(proto: "SUGGESTION_LIST_SHOW_NORMAL_RESULTS"),
    3: .same(proto: "SUGGESTION_LIST_SHOW_PREDICTIVE_RESULTS"),
  ]
}

extension Hazkey_Config_ConfigProfile.SpecialConversionMode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Hazkey_Config_ConfigProfile.protoMessageName + ".SpecialConversionMode"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "comma_separated_number"),
    2: .standard(proto: "mail_domain"),
    3: .same(proto: "calender"),
    4: .same(proto: "time"),
    5: .standard(proto: "roman_typography"),
    6: .standard(proto: "unicode_codepoint"),
    7: .standard(proto: "hazkey_version"),
    50: .standard(proto: "halfwidth_katakana"),
    51: .standard(proto: "extended_emoji"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.commaSeparatedNumber) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.mailDomain) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.calender) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.time) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.romanTypography) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.unicodeCodepoint) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.hazkeyVersion) }()
      case 50: try { try decoder.decodeSingularBoolField(value: &self.halfwidthKatakana) }()
      case 51: try { try decoder.decodeSingularBoolField(value: &self.extendedEmoji) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.commaSeparatedNumber != false {
      try visitor.visitSingularBoolField(value: self.commaSeparatedNumber, fieldNumber: 1)
    }
    if self.mailDomain != false {
      try visitor.visitSingularBoolField(value: self.mailDomain, fieldNumber: 2)
    }
    if self.calender != false {
      try visitor.visitSingularBoolField(value: self.calender, fieldNumber: 3)
    }
    if self.time != false {
      try visitor.visitSingularBoolField(value: self.time, fieldNumber: 4)
    }
    if self.romanTypography != false {
      try visitor.visitSingularBoolField(value: self.romanTypography, fieldNumber: 5)
    }
    if self.unicodeCodepoint != false {
      try visitor.visitSingularBoolField(value: self.unicodeCodepoint, fieldNumber: 6)
    }
    if self.hazkeyVersion != false {
      try visitor.visitSingularBoolField(value: self.hazkeyVersion, fieldNumber: 7)
    }
    if self.halfwidthKatakana != false {
      try visitor.visitSingularBoolField(value: self.halfwidthKatakana, fieldNumber: 50)
    }
    if self.extendedEmoji != false {
      try visitor.visitSingularBoolField(value: self.extendedEmoji, fieldNumber: 51)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_ConfigProfile.SpecialConversionMode, rhs: Hazkey_Config_ConfigProfile.SpecialConversionMode) -> Bool {
    if lhs.commaSeparatedNumber != rhs.commaSeparatedNumber {return false}
    if lhs.mailDomain != rhs.mailDomain {return false}
    if lhs.calender != rhs.calender {return false}
    if lhs.time != rhs.time {return false}
    if lhs.romanTypography != rhs.romanTypography {return false}
    if lhs.unicodeCodepoint != rhs.unicodeCodepoint {return false}
    if lhs.hazkeyVersion != rhs.hazkeyVersion {return false}
    if lhs.halfwidthKatakana != rhs.halfwidthKatakana {return false}
    if lhs.extendedEmoji != rhs.extendedEmoji {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_Config_ConfigProfile.InputTable: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Hazkey_Config_ConfigProfile.protoMessageName + ".InputTable"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .standard(proto: "is_default"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isDefault) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.isDefault != false {
      try visitor.visitSingularBoolField(value: self.isDefault, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_ConfigProfile.InputTable, rhs: Hazkey_Config_ConfigProfile.InputTable) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.isDefault != rhs.isDefault {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_Config_ConfigProfile.ZenzaiVersionConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Hazkey_Config_ConfigProfile.protoMessageName + ".ZenzaiVersionConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "v1"),
    2: .same(proto: "v2"),
    3: .same(proto: "v3"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V1?
        var hadOneofValue = false
        if let current = self.version {
          hadOneofValue = true
          if case .v1(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.version = .v1(v)
        }
      }()
      case 2: try {
        var v: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V2?
        var hadOneofValue = false
        if let current = self.version {
          hadOneofValue = true
          if case .v2(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.version = .v2(v)
        }
      }()
      case 3: try {
        var v: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V3?
        var hadOneofValue = false
        if let current = self.version {
          hadOneofValue = true
          if case .v3(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.version = .v3(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.version {
    case .v1?: try {
      guard case .v1(let v)? = self.version else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .v2?: try {
      guard case .v2(let v)? = self.version else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .v3?: try {
      guard case .v3(let v)? = self.version else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig, rhs: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig) -> Bool {
    if lhs.version != rhs.version {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.protoMessageName + ".V1"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V1, rhs: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V1) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V2: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.protoMessageName + ".V2"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "profile"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.profile) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.profile.isEmpty {
      try visitor.visitSingularStringField(value: self.profile, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V2, rhs: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V2) -> Bool {
    if lhs.profile != rhs.profile {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V3: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.protoMessageName + ".V3"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "profile"),
    2: .same(proto: "topic"),
    3: .same(proto: "style"),
    4: .same(proto: "preference"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.profile) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.topic) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.style) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.preference) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.profile.isEmpty {
      try visitor.visitSingularStringField(value: self.profile, fieldNumber: 1)
    }
    if !self.topic.isEmpty {
      try visitor.visitSingularStringField(value: self.topic, fieldNumber: 2)
    }
    if !self.style.isEmpty {
      try visitor.visitSingularStringField(value: self.style, fieldNumber: 3)
    }
    if !self.preference.isEmpty {
      try visitor.visitSingularStringField(value: self.preference, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V3, rhs: Hazkey_Config_ConfigProfile.ZenzaiVersionConfig.V3) -> Bool {
    if lhs.profile != rhs.profile {return false}
    if lhs.topic != rhs.topic {return false}
    if lhs.style != rhs.style {return false}
    if lhs.preference != rhs.preference {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_Config_ConfigProfile.ZenzaiModel: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Hazkey_Config_ConfigProfile.protoMessageName + ".ZenzaiModel"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .same(proto: "filename"),
    3: .standard(proto: "is_system"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.filename) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isSystem) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.filename.isEmpty {
      try visitor.visitSingularStringField(value: self.filename, fieldNumber: 2)
    }
    if self.isSystem != false {
      try visitor.visitSingularBoolField(value: self.isSystem, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_ConfigProfile.ZenzaiModel, rhs: Hazkey_Config_ConfigProfile.ZenzaiModel) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.filename != rhs.filename {return false}
    if lhs.isSystem != rhs.isSystem {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_Config_getCurrentConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".getCurrentConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_getCurrentConfig, rhs: Hazkey_Config_getCurrentConfig) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_Config_setConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".setConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "hash"),
    2: .standard(proto: "table_operations"),
    3: .same(proto: "config"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._hash) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.tableOperations) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.config) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._hash {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.tableOperations.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.tableOperations, fieldNumber: 2)
    }
    if !self.config.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.config, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_setConfig, rhs: Hazkey_Config_setConfig) -> Bool {
    if lhs._hash != rhs._hash {return false}
    if lhs.tableOperations != rhs.tableOperations {return false}
    if lhs.config != rhs.config {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_Config_getDefaultConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".getDefaultConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_getDefaultConfig, rhs: Hazkey_Config_getDefaultConfig) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_Config_clearAllHistory: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".clearAllHistory"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_clearAllHistory, rhs: Hazkey_Config_clearAllHistory) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_Config_CurrentConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CurrentConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "hash"),
    2: .standard(proto: "input_tables"),
    3: .same(proto: "configs"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._hash) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.inputTables) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.configs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._hash {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.inputTables.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.inputTables, fieldNumber: 2)
    }
    if !self.configs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.configs, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_CurrentConfig, rhs: Hazkey_Config_CurrentConfig) -> Bool {
    if lhs._hash != rhs._hash {return false}
    if lhs.inputTables != rhs.inputTables {return false}
    if lhs.configs != rhs.configs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
